hunav_loader:
  ros__parameters:
    simulator: Isaac Sim
    map: warehouse
    yaml_base_name: warehouse_agents_jun18
    publish_people: true
    global_goals:
      1:
        x: -5.477
        y: 9.210
      2:
        x: 0.851
        y: 7.200
      3:
        x: 6.915
        y: 2.234
      4:
        x: 0.169
        y: 1.893
      5:
        x: -6.615
        y: -0.041
      6:
        x: -0.096
        y: -3.112
    agents:
      - agent1
      - agent2
    agent1:
      id: 1
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -6.797
        y: 2.953
        z: 0.000
        h: -0.025
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 1
        - 2
        - 3
    agent2:
      id: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 6.003
        y: 9.696
        z: 0.000
        h: -2.405
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      goals:
        - 4
        - 5
        - 6
        
