hunav_loader:
  ros__parameters:
    map: hospital
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
      - agent6
      - agent7
      - agent8
      - agent9
    agent1:
      id: 1
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1    # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0  # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seconds
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: -9.5
        y: -1.7
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -10.5
        y: 2.0
        h: 0.0
      g1:
        x: -2.5
        y: 2.0
        h: 0.0
      g2:
        x: -5.0
        y: -1.9
        h: 0.0

    agent2:
      id: 2
      skin: 3
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: -1.9
        y: 4.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -28.0
        y: 5.0
        h: 0.0
      g1:
        x: -24.0
        y: 3.0
        h: 0.0
      g2:
        x: -15.0
        y: 3.5
        h: 0.0

    agent3:
      id: 3
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: 2.0
        y: -2.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -11.0
        y: 0.0
        h: 0.0
      g1:
        x: -5.0
        y: 4.0
        h: 0.0
      g2:
        x: 9.0
        y: 0.0
        h: 0.0

    agent4:
      id: 4
      skin: 3
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: -32.0
        y: 3.5
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -19.0
        y: 4.0
        h: 0.0
      g1:
        x: -1.0
        y: 1.0
        h: 0.0
      g2:
        x: -8.0
        y: 4.5
        h: 0.0

    agent5:
      id: 5
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: 5.0
        y: 6.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 8.0
        y: -1.5
        h: 0.0
      g1:
        x: 4.0
        y: 0.0
        h: 0.0
      g2:
        x: 8.0
        y: 5.0
        h: 0.0

    agent6:
      id: 6
      skin: 3
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: -31.0
        y: 9.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -29.5
        y: 3.5
        h: 0.0
      g1:
        x: -26.0
        y: 12.0
        h: 0.0
      g2:
        x: -28.0
        y: 16.5
        h: 0.0

    agent7:
      id: 7
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: 1.0
        y: 10.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -17.0
        y: 11.0
        h: 0.0
      g1:
        x: -28.0
        y: 10.0
        h: 0.0
      g2:
        x: -7.0
        y: 11.0
        h: 0.0

    agent8:
      id: 8
      skin: 3
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: -32.0
        y: 12.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -20.0
        y: 10.0
        h: 0.0
      g1:
        x: -1.0
        y: 11.5
        h: 0.0
      g2:
        x: 5.0
        y: 9.0
        h: 0.0

    agent9:
      id: 9
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: 19.0
        y: 4.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 5.0
        y: 11.0
        h: 0.0
      g1:
        x: 6.0
        y: -2.0
        h: 0.0
      g2:
        x: 14.0
        y: 9.0
        h: 0.0
