hunav_loader:
  ros__parameters:
    map: warehouse
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
      - agent5
    agent1:
      id: 1
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1     # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seconds
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: -6.5
        y: 0.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -4.0
        y: 14.0
        h: 0.0
      g1:
        x: 0.0
        y: 9.0
        h: 0.0
      g2:
        x: -4.0
        y: -6.0
        h: 0.0

    agent2:
      id: 2
      skin: 3
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1
        configuration: 2
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: -1.0
        y: -3.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 2.0
        y: 14.0
        h: 0.0
      g1:
        x: -5.0
        y: 6.0
        h: 0.0
      g2:
        x: 3.0
        y: 0.0
        h: 0.0

    agent3:
      id: 3
      skin: 3
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1       
        configuration: 2
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: 6.0
        y: 7.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 4.0
        y: -6.0
        h: 0.0
      g1:
        x: -1.5
        y: 0.5
        h: 0.0
      g2:
        x: -3.0
        y: 10.0
        h: 0.0

    agent4:
      id: 4
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1        
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: -5.0
        y: 9.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 5.0
        y: 11.0
        h: 0.0
      g1:
        x: 1.5
        y: 4.0
        h: 0.0
      g2:
        x: -1.5
        y: -8.0
        h: 0.0

    agent5:
      id: 5
      skin: 3         
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior:
        type: 1        
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 5.0
        obstacle_force_factor: 150.0
        social_force_factor: 10.0
        other_force_factor: 20.0
      init_pose:
        x: 0.0
        y: 14.0
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: 3.0
        y: 6.5
        h: 0.0
      g1:
        x: -4.5
        y: -1.0
        h: 0.0
      g2:
        x: -1.0
        y: 7.0
        h: 0.0
