hunav_loader:
  ros__parameters:
    map: sample_scenario_2
    publish_people: true
    agents:
      - agent1
    agent1:
      id: 1
      skin: 3 #omniverse://localhost/NVIDIA/Assets/Isaac/4.2/Isaac/People/Characters/F_Business_02/F_Business_02.usd
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 6 
        configuration: 2  
        duration: 40.0  # seg
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 150.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 2.924233
        y: 5.007970
        z: 0.0
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -11.924233
        y: 5.007970
        h: 0.0
      g1:
        x: -1.663169
        y: -11.291318
        h: 0.0
